### ISSUE TITLE
bookmark-sidebar without new tab 

### ISSUE THREAD

**Issue by 90999** [lennyanders/bookmark-sidebar#3]
your bookmark-sidebar is so good for ms edge , it looks like firefox bookmarks bar and easy to use . 
but  new tab is unuseable for edge , and can you rebuild new app without new tab , so i can use other new tab toolbar .

**Comment by 5onderling** [comment]
Thank you very much.
I personally switched to Firefox a while ago and didn't develop this extension any further, although I have a list of things I wanted to implement. One of them is what you ask for here.

I also think the version in the Microsoft Edge and Chrome extension stores isn't actually the same with what I have here on GitHub, so the design and implementation would be quite different if I update the extension.

When you install the extension, I think Chrome asks you if you want to keep the changed new tab page. So I guess disagreeing there could be a quick fix?
I just tested it and yeah, I guess I need to update the extension. I don't have much Time currently, but I see if I can implement it within the 2 or maybe 3 weeks.

**Comment by 5onderling** [comment]
Hey,
I implemented the feature and submitted a new version to the Microsoft Edge Extension store. When it is live I will close this issue.

**Comment by 5onderling** [comment]
The new version is now live in Microsoft Edge Extension store.
